### ISSUE TITLE
Really slow on updates.

### ISSUE THREAD

**Issue by vegetablesalad** [forteleaf/sketkchybar-with-aerospace#4]
Does it have a big delay for everyone when updating active workspace?
It takes some 500ms to highlight the active workspace I switched to.

**Comment by vegetablesalad** [comment]
I checked that `exec-on-workspace-change` in aerospace is instantaneous, so it must something in the sketchybar config. Will look into this when I get some free time and if it is not resolved, hope someone can address this faster as free time is scarce recently.

**Comment by GrimalDev** [comment]
Sorry to resurrect this closed issue, but I have successfully greatly reduced the latency on workspace change. (this has been bugging me for quite some time on my config)

## The changes are:

- Less aerospace calls
- Less sketchybar calls (grouped)
- A very basic cache system for apps infos

## The main changes are in the space_windows.sh plugin file

https://github.com/GrimalDev/dotfiles/blob/aerospace/sketchybar/plugins/space_windows.sh

## Conclusion

I deeply think that all of this is cause because of the very bad readability of the bash language.
I advise moving to another language, like the well known lua for configs. (I see that you have done so yourself too @forteleaf )
